development:
  adapter: postgresql
  encoding: utf8
  database: skibike_development
  pool: 5
  username: sobaka
  password:
  template: template0

test:
  adapter: postgresql
  encoding: utf8
  database: skibike_test
  pool: 5
  username: sobaka
  password:
  template: template0


production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
