# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1614fb5614058b914d37339e2d9f9d37ad9d78e24a23db5b96574d5d59f7ff32e46e4a0f0121e8656bccc13664a8ac4e2d66fd143e5b65a03bc67a2e0af2d249
  merchant_login: ski-bike
  merchant_pass_1: NTbWMX5mL4k
  merchant_pass_2: yYpaWcdJI9k
  notifications_email: sale@spine-sport.ru
  aws_access_key_id:  <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_KEY"] %>
  s3_bucket: ski-bike-dev

test:
  secret_key_base: d85c5da5128918addec5ec99b847e9d570d0e36fefd7a0b95210df3e03fab08537ee10603c411406fdc804a645e85f2b08dcea2a8c456682450f34226cd22b14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_login: <%= ENV["ADMIN_LOGIN"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  merchant_login: <%= ENV["MERCHANT_LOGIN"] %>
  merchant_pass_1: <%= ENV["MERCHANT_PASS_1"] %>
  merchant_pass_2: <%= ENV["MERCHANT_PASS_2"] %>
  notifications_email: <%= ENV["NOTIFICATIONS_EMAIL"] %>
  aws_access_key_id:  <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_KEY"] %>
  s3_bucket: <%= ENV["S3_BUCKET"] %>
  mailer_username: <%= ENV["MAILER_USERNAME"]%>
  mailer_password: <%= ENV["MAILER_PASSWORD"]%>
  ones_username:  <%= ENV["ONES_USERNAME"]%>
  ones_password:  <%= ENV["ONES_PASSWORD"]%>
